name: "✅ Task"
description: "Track implementation, integration, or setup work"

body:
  - type: dropdown
    id: component
    attributes:
      label: "🔍 Component"
      description: "Which component does this task involve?"
      options:
        - backend
        - frontend
        - database
        - infrastructure
    validations:
      required: true

  - type: dropdown
    id: task_type
    attributes:
      label: "🏗️ Task Type"
      description: "What kind of task is this?"
      options:
        - implementation
        - integration
        - setup
        - testing
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "📋 Task Description"
      description: "What needs to be done?"
      placeholder: |
        Clear description of the work required:
        - Specific implementation details
        - Dependencies or prerequisites
        - Expected outcome
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: "✅ Completion Criteria"
      description: "What defines this task as complete?"
      placeholder: |
        - [ ] Specific requirement 1
        - [ ] Specific requirement 2
        - [ ] Tests added/updated
        - [ ] Documentation updated
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: "🎯 Priority"
      description: "Task priority level"
      options:
        - high
        - medium
        - low
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: "📝 Additional Notes"
      description: "Any other relevant information"
      placeholder: "Technical details, links to resources, etc."
    validations:
      required: false
