name: 📋 Task
description: "Create a new development task"
title: "📋 "
labels: []
projects: ["socrabytes/6"]
body:
  - type: markdown
    attributes:
      value: |
        ## Let's Add Some Tags to This Task! 🏷️
        
        To keep things organized, please add appropriate labels:

        ### Component Labels (choose one)
        `backend` | `frontend` | `database` | `infrastructure`

        ### Priority Labels (choose one)
        `high` | `medium` | `low`

        ### Project Phase (Add to milestone)
        Phase 1: Basic Infrastructure
        Phase 2: Video Processing
        Phase 3: Enhanced UX
        Phase 4: Advanced Features

        > ⚠️ Please ensure you've added appropriate labels before submitting the task.

  - type: markdown
    attributes:
      value: |
        ## User Story
        Please provide the user story in the format below.

  - type: textarea
    id: user-story
    attributes:
      label: User Story
      placeholder: |
        As a user,
        I want [feature/capability]
        So that [benefit/value]

  - type: markdown
    attributes:
      value: |
        ## Task Description
        Please provide a clear description of the task.

  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: |
        Technical Details:
        - Implementation requirements
        - Dependencies/prerequisites
        - Expected behavior/outcome
        - Technical constraints
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Acceptance Criteria
        What needs to be completed for this task to be considered done?

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      placeholder: |
        - [ ] Implementation requirement 1
        - [ ] Implementation requirement 2
        - [ ] Tests added/updated
        - [ ] Documentation updated if needed
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Implementation Guide
        Provide any technical details or guidelines for implementation.

  - type: textarea
    id: implementation_guide
    attributes:
      label: Implementation Guide
      placeholder: |
        Branch Naming Convention:
        <type>/<issue-number>-<short-description>

        Types:
        - feat/    : New features
        - fix/     : Bug fixes
        - docs/    : Documentation
        - refactor/: Code refactoring
        - test/    : Testing
        - chore/   : Maintenance

        Example: feat/42-add-video-processing

        Technical Notes:
        - Architecture considerations
        - Design patterns
        - Performance requirements
