name: "✅ Task"
description: "Create a new development task"
title: "[Task] "
projects: ["socrabytes/6"]

body:
  - type: markdown
    attributes:
      label: "🏷️ Labels Guide"
      value: |
        ### Component Labels (Add one)
        `backend` | `frontend` | `database` | `infrastructure`

        ### Priority Labels (Add one)
        `high` | `medium` | `low`

        ### Project Phase (Add to milestone)
        Phase 1: Basic Infrastructure
        Phase 2: Video Processing
        Phase 3: Enhanced UX
        Phase 4: Advanced Features

  - type: checkboxes
    id: confirmation
    attributes:
      label: "📝 Task Setup Confirmation"
      description: "Confirm you've set up the task properly"
      options:
        - label: "I have added appropriate labels"
          required: true

  - type: textarea
    id: description
    attributes:
      label: "📋 Task Description"
      description: "Technical requirements and expected outcome"
      placeholder: |
        Technical Details:
        - Implementation requirements
        - Dependencies/prerequisites
        - Expected behavior/outcome
        - Technical constraints
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: "✅ Acceptance Criteria"
      description: "Clear, testable requirements that define completion"
      placeholder: |
        - [ ] Implementation requirement 1
        - [ ] Implementation requirement 2
        - [ ] Tests added/updated
        - [ ] Documentation updated if needed
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: "🛠️ Implementation Guide"
      description: "Technical guidance for implementation"
      placeholder: |
        Branch Naming Convention:
        <type>/<issue-number>-<short-description>

        Types:
        - feat/    : New features
        - fix/     : Bug fixes
        - docs/    : Documentation
        - refactor/: Code refactoring
        - test/    : Testing
        - chore/   : Maintenance

        Example: feat/42-add-video-processing

        Technical Notes:
        - Architecture considerations
        - Design patterns
        - Performance requirements
    validations:
      required: false
