name: "Task"
description: Create a new task
title: "[Task] "
labels: []
projects: ["socrabytes/6"]
body:
  - type: markdown
    attributes:
      value: |
        📋 Task Setup Confirmation

  - type: dropdown
    id: setup_confirmation
    attributes:
      label: Task Setup Confirmation
      description: Please confirm you have added appropriate labels
      options:
        - "✅ Yes, I have added appropriate labels"
        - "❌ No, I still need to add labels"
      default: 1
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Task Description
        Please provide a clear description of the task.

  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: Describe the task here...
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Acceptance Criteria
        What needs to be completed for this task to be considered done?

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      placeholder: List the acceptance criteria...
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Implementation Guide
        Provide any technical details or guidelines for implementation.

  - type: textarea
    id: implementation_guide
    attributes:
      label: Implementation Guide
      placeholder: Add implementation details...
