name: "✨ Feature Request"
description: "Propose a new feature or enhancement"

body:
  - type: dropdown
    id: component
    attributes:
      label: "🔍 Component"
      description: "Which part of the project does this feature affect?"
      options:
        - backend
        - frontend
        - database
        - infrastructure
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: "🎯 Priority"
      description: "How critical is this feature?"
      options:
        - high
        - medium
        - low
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "💡 Description"
      description: "Provide a clear explanation of the feature and its purpose"
      placeholder: "Describe the feature and the problem it solves"
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: "✅ Acceptance Criteria"
      description: "List the conditions that must be met for the feature to be complete"
      placeholder: |
        - [ ] The API endpoint returns the correct data
        - [ ] The UI displays the new button
    validations:
      required: true
