name: "Bug Report"
description: Report a bug or issue
title: "[Bug] "
labels: ["bug"]
projects: ["socrabytes/6"]

body:
  - type: markdown
    attributes:
      value: |
        🔍 Prerequisites

  - type: dropdown
    id: prerequisites
    attributes:
      label: Bug Report Prerequisites
      description: Please confirm you have checked for existing issues
      options:
        - "✅ Yes, I have searched existing issues and this bug hasn't been reported yet"
        - "❌ No, I need to check existing issues first"
      default: 1
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Affected Component

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Select the affected component
      options:
        - frontend
        - backend
        - database
        - infrastructure
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Bug Severity

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: How severe is this bug?
      options:
        - high (Critical functionality broken)
        - medium (Important feature affected)
        - low (Minor issue/cosmetic problem)
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Bug Details

  - type: textarea
    id: current_behavior
    attributes:
      label: Current Behavior
      description: What is happening?
      placeholder: Describe the bug in detail...
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: What should happen?
      placeholder: Describe what you expected...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context about the problem?
      placeholder: Add any other relevant information...
