name: "🐛 Bug Report"
description: "Report an issue or unexpected behavior"
title: "🐛 "
labels: ["bug"]
projects: ["socrabytes/6"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        Before proceeding, please ensure the issue you're reporting is:
        - not a duplicate of an existing issue ([check open issues](https://github.com/socrabytes/youtube-digest/issues))
        - not a feature request or general question (use [GitHub Discussions](https://github.com/socrabytes/youtube-digest/discussions) instead)
        - reproducible and not specific to your local setup

  - type: checkboxes
    id: prerequisites
    attributes:
      label: "Prerequisites"
      options:
        - label: "I have searched existing issues and this bug hasn't been reported yet"
          required: true

  - type: markdown
    attributes:
      value: |
        ## Affected Component

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Select the affected component
      options:
        - frontend (User Interface)
        - backend (Server/API)
        - database (Data Storage)
        - infrastructure (System Setup)
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Bug Severity

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: How severe is this bug?
      options:
        - high (Application crash/data loss)
        - medium (Feature broken but workaround exists)
        - low (Minor issue/cosmetic problem)
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Bug Details

  - type: textarea
    id: current_behavior
    attributes:
      label: Current Behavior
      description: What is happening? Be specific and clear
      placeholder: |
        Describe the bug:
        - What exactly is not working?
        - What error messages do you see?
        - When does this happen?
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: What should happen instead?
      placeholder: |
        Describe what you expected:
        - What should the application do?
        - What is the correct behavior?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Help us recreate this issue
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error

        Tip: Clear steps help us fix the bug faster!
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other information that might help?
      placeholder: |
        Examples:
        - Screenshots or videos
        - Browser version if frontend issue
        - Operating system
        - When the issue started
