name: "📚 Documentation"
description: "Suggest improvements or additions to documentation"

body:
  - type: dropdown
    id: doc_type
    attributes:
      label: "📑 Documentation Type"
      description: "What type of documentation needs work?"
      options:
        - readme
        - api
        - setup
        - usage
        - contributing
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: "🔍 Component"
      description: "Which component's documentation needs updating?"
      options:
        - backend
        - frontend
        - database
        - infrastructure
        - general
    validations:
      required: true

  - type: textarea
    id: current_docs
    attributes:
      label: "📝 Current Documentation"
      description: "Describe the current documentation (if it exists)"
      placeholder: "What does the current documentation say or lack?"
    validations:
      required: false

  - type: textarea
    id: proposed_changes
    attributes:
      label: "✨ Proposed Changes"
      description: "Describe what should be added or modified"
      placeholder: |
        - What should be added?
        - What should be clarified?
        - Any specific examples to include?
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: "📌 Additional Context"
      description: "Any other context or screenshots"
      placeholder: "Add any other context about the documentation changes"
    validations:
      required: false
