name: Feature Request
description: Propose a new feature or enhancement.

body:
  - type: input
    id: title
    attributes:
      label: Title
      description: A concise title for the feature request.
      placeholder: "e.g., Add user authentication to the login page"
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the project does this feature affect?
      options:
        - label: backend
          description: Backend services (e.g., API, business logic)
        - label: frontend
          description: User interface and client-side logic
        - label: database
          description: Database schema or performance improvements
        - label: infrastructure
          description: CI/CD, deployment, or tooling
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How critical is this feature?
      options:
        - label: high
          description: Critical or blocking progress
        - label: medium
          description: Important but not blocking
        - label: low
          description: Nice-to-have
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a clear explanation of the feature and its purpose.
      placeholder: "Describe the feature and the problem it solves."
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: List the conditions that must be met for the feature to be complete.
      placeholder: |
        Example:
        - [ ] The API endpoint returns the correct data
        - [ ] The UI displays the new button
    validations:
      required: true
