"""Add token usage tracking and summary style

Revision ID: 03b3983b0790
Revises: 9395fe64ef7e
Create Date: 2025-02-03 22:33:24.479298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03b3983b0790'
down_revision = '9395fe64ef7e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
