"""🗃️ fix(db): add server defaults for JSON fields

Revision ID: 0545b09ab800
Revises: 7fde510c2388
Create Date: 2024-12-13 16:16:36.313292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0545b09ab800'
down_revision = '7fde510c2388'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
