"""remove_summary_style_field

Revision ID: 6dfc2be44bb5
Revises: 03b3983b0790
Create Date: 2025-02-03 23:04:14.038512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dfc2be44bb5'
down_revision = '03b3983b0790'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'summary_style')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('summary_style', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
