"""✨ feat(db): add enhanced video metadata fields

Revision ID: d036c8bb705d
Revises: 1a2b3c4d5e6f
Create Date: 2024-12-13 15:55:44.267500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd036c8bb705d'
down_revision = '1a2b3c4d5e6f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('duration', sa.Integer(), nullable=True))
    op.add_column('videos', sa.Column('view_count', sa.BigInteger(), nullable=True))
    op.add_column('videos', sa.Column('channel_id', sa.String(length=50), nullable=True))
    op.add_column('videos', sa.Column('channel_title', sa.String(length=255), nullable=True))
    op.add_column('videos', sa.Column('tags', sa.JSON(), nullable=True))
    op.add_column('videos', sa.Column('categories', sa.JSON(), nullable=True))
    op.add_column('videos', sa.Column('transcript', sa.Text(), nullable=True))
    op.add_column('videos', sa.Column('sentiment_score', sa.Integer(), nullable=True))
    op.add_column('videos', sa.Column('error_message', sa.Text(), nullable=True))
    op.alter_column('videos', 'youtube_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_constraint('videos_youtube_id_key', 'videos', type_='unique')
    op.create_index(op.f('ix_videos_id'), 'videos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_videos_id'), table_name='videos')
    op.create_unique_constraint('videos_youtube_id_key', 'videos', ['youtube_id'])
    op.alter_column('videos', 'youtube_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('videos', 'error_message')
    op.drop_column('videos', 'sentiment_score')
    op.drop_column('videos', 'transcript')
    op.drop_column('videos', 'categories')
    op.drop_column('videos', 'tags')
    op.drop_column('videos', 'channel_title')
    op.drop_column('videos', 'channel_id')
    op.drop_column('videos', 'view_count')
    op.drop_column('videos', 'duration')
    # ### end Alembic commands ###
