name: Move Issues to Project Columns

on:
  issues:
    types: [labeled]

env:
  PROJECT_ID: "PVT_kwHOBpT7s84Auc0_"   # Static Project ID
  STATUS_FIELD_ID: "PVTSSF_lAHOBpT7s84Auc0_zglCzjk"   # Static Field ID for "Status"
  BUGS_OPTION_ID: "46438b8c"   # Static Option ID for "🪳Bugs"

jobs:
  print_context:
    runs-on: ubuntu-latest
    steps:
      - name: Print Event Context
        env:
          EVENT_CONTEXT: ${{ toJson(github.event) }}
        run: |
          echo $EVENT_CONTEXT
          echo "Issue Number: ${{ github.event.issue.number }}"
          echo "Issue Title: ${{ github.event.issue.title }}"
          echo "Repository: ${{ github.repository }}"
          echo "Label Name: ${{ github.event.label.name }}"

  run_if_label_matches:
    if: github.event.label.name == 'bug'
    runs-on: ubuntu-latest
    permissions:
      repository-projects: write
    steps:
      - name: Move Issue to 🪳Bugs Column
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get the Issue Number from the Event
          ISSUE_NUMBER=${{ github.event.issue.number }}
          REPO=${{ github.repository }}

          # Fetch the Project Item ID for the Issue
          ITEM_ID=$(gh issue view $ISSUE_NUMBER --json projectItems --jq ".projectItems[] | select(.project.id == '${{ env.PROJECT_ID }}') | .id")

          if [ -z "$ITEM_ID" ]; then
            echo "Error: Could not retrieve Project Item ID for issue #$ISSUE_NUMBER."
            exit 1
          fi

          # Move the Issue to the 🪳Bugs Column
          gh project item-edit \
            --id "$ITEM_ID" \
            --field-id "${{ env.STATUS_FIELD_ID }}" \
            --project-id "${{ env.PROJECT_ID }}" \
            --single-select-option-id "${{ env.BUGS_OPTION_ID }}"